[pytest]
; Test discovery process, matching tests directory
; Also restrict test discovery to patterned modules, classes, and functions.
python_files = test_*.py
python_classes = Test* *Test *Tests *Tester
python_functions = test_* test[A-Z]*
