""" Package constants """

__author__ = "Michal Stolarczyk"
__email__ = "michal@virginia.edu"

# Project-related
NAME_KEY = "name"
CONFIG_VERSION_KEY = "pep_version"
CONFIG_FILE_KEY = "_config_file"
CONFIG_KEY = "_config"
PROJECT_TYPENAME = "Project"
MODIFIERS_KEY = "sample_modifiers"
NAME_TABLE_ATTR = "sample_table"
CONSTANT_KEY = "append"
DUPLICATED_KEY = "duplicate"
DERIVED_KEY = "derive"
DERIVED_SOURCES_KEY = "sources"
DERIVED_ATTRS_KEY = "attributes"
IMPLIED_KEY = "imply"
IMPLIED_THEN_KEY = "then"
IMPLIED_IF_KEY = "if"
IMPLIED_COND_KEYS = [IMPLIED_IF_KEY, IMPLIED_THEN_KEY]
METADATA_KEY = "metadata"
OUTDIR_KEY = "output_dir"
CFG_IMPORTS_KEY = "imports"
AMENDMENTS_KEY = "amendments"
ACTIVE_AMENDMENTS_KEY = "_" + AMENDMENTS_KEY
SAMPLE_EDIT_FLAG_KEY = "_samples_touched"
SAMPLE_MODIFIERS = [CONSTANT_KEY, IMPLIED_KEY, DERIVED_KEY, DUPLICATED_KEY]
PROJECT_CONSTANTS = [
    "CONSTANT_KEY", "DERIVED_SOURCES_KEY", "DERIVED_KEY", "MODIFIERS_KEY",
    "IMPLIED_KEY", "METADATA_KEY", "NAME_TABLE_ATTR", "OUTDIR_KEY",
    "CONFIG_FILE_KEY", "CONFIG_KEY", "NAME_KEY",
    "AMENDMENTS_KEY", "PROJECT_TYPENAME", "SAMPLE_MODIFIERS",
    "CONFIG_VERSION_KEY", "DUPLICATED_KEY", "SAMPLE_EDIT_FLAG_KEY",
    "CFG_IMPORTS_KEY", "ACTIVE_AMENDMENTS_KEY", "DERIVED_ATTRS_KEY",
    "IMPLIED_COND_KEYS", "IMPLIED_IF_KEY", "IMPLIED_THEN_KEY"]

# Sample-related
PROTOCOL_KEY = "protocol"
SAMPLE_NAME_ATTR = "sample_name"
SUBSAMPLE_NAME_ATTR = "subsample_name"
SAMPLE_SHEET_KEY = "sample_sheet"
SUBSAMPLE_SHEET_KEY = "subsample_sheet"
CFG_SAMPLE_TABLE_KEY = "sample_table"
CFG_SUBSAMPLE_TABLE_KEY = "subsample_table"
SAMPLE_DF_KEY = "_sample_df"
SUBSAMPLE_DF_KEY = "_subsample_df"
PRJ_REF = "_project"
ATTR_KEY_PREFIX = "_key_"
SAMPLE_CONSTANTS = [
    "PROTOCOL_KEY", "SUBSAMPLE_SHEET_KEY", "SAMPLE_SHEET_KEY", "PRJ_REF",
    "SAMPLE_NAME_ATTR", "ATTR_KEY_PREFIX", "CFG_SAMPLE_TABLE_KEY",
    "CFG_SUBSAMPLE_TABLE_KEY", "SAMPLE_DF_KEY", "SUBSAMPLE_DF_KEY",
    "SUBSAMPLE_NAME_ATTR"]

# CLI
VALIDATE_CMD = "validate"
INSPECT_CMD = "inspect"
SUBPARSER_MSGS = {
    VALIDATE_CMD: "Validate the PEP or its components.",
    INSPECT_CMD: "Inspect a PEP."
}

CLI_CONSTANTS = ["VALIDATE_CMD", "INSPECT_CMD", "SUBPARSER_MSGS"]

# Other
PKG_NAME = "peppy"
MAX_PROJECT_SAMPLES_REPR = 20
MODIFIERS_MOVE_PAIRS = {
    "derived_attributes": [DERIVED_KEY, DERIVED_ATTRS_KEY],
    "derived_columns": DERIVED_KEY,
    "constant_attributes": CONSTANT_KEY,
    "implied_attributes": IMPLIED_KEY,
    "implied_columns": IMPLIED_KEY,
    "data_sources": [DERIVED_KEY, DERIVED_SOURCES_KEY]
}
OTHER_CONSTANTS = [
    "MAX_PROJECT_SAMPLES_REPR", "PKG_NAME", "MODIFIERS_MOVE_PAIRS"]


__all__ = PROJECT_CONSTANTS + SAMPLE_CONSTANTS + OTHER_CONSTANTS + CLI_CONSTANTS
