""" Package constants """

__author__ = "Michal Stolarczyk"
__email__ = "michal@virginia.edu"

# Project-related
CONFIG_VERSION_KEY = "config_version"
CONFIG_FILE_KEY = "_config_file"
CONFIG_KEY = "_config"
PROJECT_TYPENAME = "Project"
MODIFIERS_KEY = "sample_modifiers"
NAME_TABLE_ATTR = "sample_table"
CONSTANTS_KEY = "constants"
SYNONYMS_KEY = "synonyms"
DERIVED_SOURCES_KEY = "derived_sources"
DERIVED_KEY = "derived"
IMPLIED_KEY = "implied"
METADATA_KEY = "metadata"
OUTDIR_KEY = "output_dir"
SAMPLE_INDEPENDENT_PROJECT_SECTIONS = [METADATA_KEY, DERIVED_KEY, IMPLIED_KEY]
SUBPROJECTS_KEY = "subprojects"
PIPE_ARGS_SECTION = "pipeline_args"
SUBMISSION_FOLDER_KEY = "submission_subdir"
RESULTS_FOLDER_KEY = "results_subdir"
SAMPLE_EDIT_FLAG_KEY = "_samples_touched"
PROJECT_CONSTANTS = [
    "CONSTANTS_KEY", "DERIVED_SOURCES_KEY", "DERIVED_KEY", "MODIFIERS_KEY",
    "IMPLIED_KEY", "METADATA_KEY", "NAME_TABLE_ATTR", "OUTDIR_KEY",
    "PIPE_ARGS_SECTION", "RESULTS_FOLDER_KEY", "CONFIG_FILE_KEY", "CONFIG_KEY",
    "SAMPLE_INDEPENDENT_PROJECT_SECTIONS", "SUBMISSION_FOLDER_KEY",
    "SUBPROJECTS_KEY", "PROJECT_TYPENAME", "CONFIG_VERSION_KEY", "SYNONYMS_KEY",
    "SAMPLE_EDIT_FLAG_KEY"]
SNAKEMAKE_SAMPLE_COL = "sample"

# Sample-related
PROTOCOL_KEY = "protocol"
SAMPLE_NAME_ATTR = "sample_name"
SAMPLE_TABLE_KEY = "sample_table"
SUBSAMPLE_TABLE_KEY = "subsample_table"
PRJ_REF = "_project"
ATTR_KEY_PREFIX = "_key_"
SAMPLE_CONSTANTS = ["PROTOCOL_KEY", "SAMPLE_TABLE_KEY", "SUBSAMPLE_TABLE_KEY",
                    "PRJ_REF", "SAMPLE_NAME_ATTR", "ATTR_KEY_PREFIX"]

# Other
PKG_NAME = "peppy"
MAX_PROJECT_SAMPLES_REPR = 20
OTHER_CONSTANTS = ["MAX_PROJECT_SAMPLES_REPR", "PKG_NAME"]

__all__ = PROJECT_CONSTANTS + SAMPLE_CONSTANTS + OTHER_CONSTANTS
